export interface Client {
  id: number;
  name: string;
  progress: number;
  lastWorkout: string;
  startDate: string;
  subscriptionPlan: "Premium" | "Standard" | "Basic";
  isOnline: boolean;
  currentWeight: number;
  targetWeight: number;
  bodyFat: number;
  muscleMass: number;
  water: number;
  bmi: number;
  workoutsCompleted: number;
  caloriesBurned: number;
  exercisesCompleted: number;
}

export const MOCK_CLIENTS: Client[] = [
  {
    id: 1,
    name: "Alex Turner",
    progress: 68,
    lastWorkout: "2 days ago",
    startDate: "Jan 15, 2025",
    subscriptionPlan: "Premium",
    isOnline: true,
    currentWeight: 185,
    targetWeight: 175,
    bodyFat: 18,
    muscleMass: 42,
    water: 60,
    bmi: 27.3,
    workoutsCompleted: 32,
    caloriesBurned: 12450,
    exercisesCompleted: 156,
  },
  {
    id: 2,
    name: "Emma Davis",
    progress: 85,
    lastWorkout: "Today",
    startDate: "Dec 20, 2024",
    subscriptionPlan: "Premium",
    isOnline: true,
    currentWeight: 142,
    targetWeight: 135,
    bodyFat: 22,
    muscleMass: 38,
    water: 62,
    bmi: 24.1,
    workoutsCompleted: 48,
    caloriesBurned: 15680,
    exercisesCompleted: 234,
  },
  {
    id: 3,
    name: "Ryan Martinez",
    progress: 42,
    lastWorkout: "5 days ago",
    startDate: "Feb 1, 2026",
    subscriptionPlan: "Standard",
    isOnline: false,
    currentWeight: 195,
    targetWeight: 180,
    bodyFat: 28,
    muscleMass: 39,
    water: 58,
    bmi: 28.8,
    workoutsCompleted: 12,
    caloriesBurned: 4250,
    exercisesCompleted: 68,
  },
  {
    id: 4,
    name: "Sarah Johnson",
    progress: 91,
    lastWorkout: "Yesterday",
    startDate: "Nov 10, 2024",
    subscriptionPlan: "Premium",
    isOnline: true,
    currentWeight: 138,
    targetWeight: 130,
    bodyFat: 19,
    muscleMass: 41,
    water: 63,
    bmi: 23.5,
    workoutsCompleted: 56,
    caloriesBurned: 18900,
    exercisesCompleted: 312,
  },
  {
    id: 5,
    name: "Mike Thompson",
    progress: 55,
    lastWorkout: "1 week ago",
    startDate: "Jan 8, 2026",
    subscriptionPlan: "Basic",
    isOnline: false,
    currentWeight: 210,
    targetWeight: 190,
    bodyFat: 32,
    muscleMass: 38,
    water: 56,
    bmi: 31.2,
    workoutsCompleted: 18,
    caloriesBurned: 6320,
    exercisesCompleted: 92,
  },
  {
    id: 6,
    name: "Lisa Anderson",
    progress: 78,
    lastWorkout: "3 days ago",
    startDate: "Dec 5, 2024",
    subscriptionPlan: "Standard",
    isOnline: true,
    currentWeight: 155,
    targetWeight: 145,
    bodyFat: 24,
    muscleMass: 40,
    water: 61,
    bmi: 25.8,
    workoutsCompleted: 42,
    caloriesBurned: 14220,
    exercisesCompleted: 198,
  },
  {
    id: 7,
    name: "James Wilson",
    progress: 35,
    lastWorkout: "1 week ago",
    startDate: "Jan 25, 2026",
    subscriptionPlan: "Basic",
    isOnline: false,
    currentWeight: 220,
    targetWeight: 195,
    bodyFat: 35,
    muscleMass: 37,
    water: 55,
    bmi: 32.5,
    workoutsCompleted: 8,
    caloriesBurned: 2840,
    exercisesCompleted: 45,
  },
  {
    id: 8,
    name: "Jennifer Lee",
    progress: 72,
    lastWorkout: "Yesterday",
    startDate: "Jan 12, 2025",
    subscriptionPlan: "Standard",
    isOnline: true,
    currentWeight: 148,
    targetWeight: 140,
    bodyFat: 26,
    muscleMass: 39,
    water: 60,
    bmi: 24.9,
    workoutsCompleted: 38,
    caloriesBurned: 12680,
    exercisesCompleted: 176,
  },
  {
    id: 9,
    name: "David Chen",
    progress: 89,
    lastWorkout: "Today",
    startDate: "Oct 15, 2024",
    subscriptionPlan: "Premium",
    isOnline: true,
    currentWeight: 175,
    targetWeight: 168,
    bodyFat: 16,
    muscleMass: 44,
    water: 64,
    bmi: 25.9,
    workoutsCompleted: 62,
    caloriesBurned: 20450,
    exercisesCompleted: 356,
  },
];

/**
 * Simple client mapping for quick lookups by ID
 * Maps client ID to basic info (name, email)
 */
export const CLIENT_QUICK_MAP: { [key: number]: { name: string; email: string } } = {
  1: { name: "Alex Turner", email: "alex@gym.com" },
  2: { name: "Emma Davis", email: "emma@gym.com" },
  3: { name: "Ryan Martinez", email: "ryan@gym.com" },
  4: { name: "Sarah Johnson", email: "sarah@gym.com" },
  5: { name: "Mike Thompson", email: "mike@gym.com" },
  6: { name: "Lisa Anderson", email: "lisa@gym.com" },
  7: { name: "James Wilson", email: "james@gym.com" },
  8: { name: "Jennifer Lee", email: "jennifer@gym.com" },
  9: { name: "David Chen", email: "david@gym.com" },
};
